//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EM.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;/Table&gt;
        ///  &lt;WorksheetOptions xmlns=&quot;urn:schemas-microsoft-com:office:excel&quot;&gt;
        ///   &lt;Print&gt;
        ///    &lt;ValidPrinterInfo/&gt;
        ///    &lt;VerticalResolution&gt;0&lt;/VerticalResolution&gt;
        ///   &lt;/Print&gt;
        ///   &lt;Selected/&gt;
        ///   &lt;FreezePanes/&gt;
        ///   &lt;SplitHorizontal&gt;2&lt;/SplitHorizontal&gt;
        ///   &lt;TopRowBottomPane&gt;2&lt;/TopRowBottomPane&gt;
        ///   &lt;SplitVertical&gt;1&lt;/SplitVertical&gt;
        ///   &lt;LeftColumnRightPane&gt;1&lt;/LeftColumnRightPane&gt;
        ///   &lt;ActivePane&gt;0&lt;/ActivePane&gt;
        ///   &lt;Panes&gt;
        ///    &lt;Pane&gt;
        ///     &lt;Number&gt;3&lt;/Number&gt;
        ///    &lt;/Pane&gt;
        ///    &lt;Pane&gt;
        ///     &lt;Number&gt;1&lt;/Number&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLFooter {
            get {
                return ResourceManager.GetString("XMLFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;?mso-application progid=&quot;Excel.Sheet&quot;?&gt;
        ///&lt;Workbook xmlns=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot;
        /// xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        /// xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot;
        /// xmlns:ss=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot;
        /// xmlns:html=&quot;http://www.w3.org/TR/REC-html40&quot;&gt;
        /// &lt;DocumentProperties xmlns=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///  &lt;Author&gt;j&lt;/Author&gt;
        ///  &lt;LastAuthor&gt;j&lt;/LastAuthor&gt;
        ///  &lt;Created&gt;2008-01-03T20:53:28Z&lt;/Created&gt;
        ///  &lt;LastS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XMLHeader {
            get {
                return ResourceManager.GetString("XMLHeader", resourceCulture);
            }
        }
    }
}
